"use strict";
let x = 10;
let y = 20;
let z = "Hello, TypeScript!";
console.log(x);
console.log(y);
console.log(z);
let result = undefined;
console.log(result);
result = 2;
result = "TypeScript is great!";
console.log(result);
let result2 = undefined;
result2 = 3;
console.log(result2);
